sudo: required
language: node_js
node_js:
  - "12.14.1"
install:
  - npm ci
matrix:
  fast_finish: true
  include:
    - name: 'npm audit'
      script:
          - npm run audit:ci:high
    - name: "Build"
      script:
        - npm run build
    - name: "Tests"
      script:
        - npm test
    - name: "Lint"
      script:
        - npm run lint
