sudo: required
language: node_js
node_js:
  - 12.14.1
install:
    - npm ci
matrix:
    fast_finish: true
    include:
        - name: 'Lint'
          script:
              - npm run lint
        - name: 'Tests'
          script:
              - npm test
